# Generated by Django 5.1.5 on 2025-01-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=100)),
                ('fase', models.CharField(choices=[('fase_1', 'Fase 1'), ('fase_2', 'Fase 2'), ('fase_3', 'Fase 3'), ('fase_4', 'Fase 4')], max_length=10)),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('em_andamento', 'Em Andamento'), ('desistencia_1', 'Desistência na Fase 1'), ('desistencia_2', 'Desistência na Fase 2'), ('desistencia_3', 'Desistência na Fase 3'), ('desistencia_4', 'Desistência na Fase 4')], max_length=20)),
            ],
        ),
    ]
