# Generated by Django 5.1.5 on 2025-01-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('idade', models.IntegerField()),
                ('telefone', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=2)),
                ('protocolo', models.CharField(max_length=15)),
                ('validacao_dev', models.DateTimeField()),
                ('policial_validacao', models.CharField(max_length=255)),
                ('registro_comunicacao', models.DateTimeField()),
                ('data_fato', models.DateTimeField()),
                ('natureza', models.CharField(max_length=255)),
                ('dp_apuracao', models.CharField(max_length=255)),
                ('finalizacao_atendimento', models.DateTimeField(blank=True, null=True)),
                ('policial_finalizacao', models.CharField(blank=True, max_length=255, null=True)),
                ('status_fase1', models.CharField(max_length=255)),
                ('falta_contato', models.CharField(blank=True, max_length=255, null=True)),
                ('vitima_representou', models.CharField(blank=True, max_length=255, null=True)),
                ('vitima_rep_criminal', models.CharField(blank=True, max_length=255, null=True)),
                ('caso_piloto', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
        ),
    ]
