# Generated by Django 5.1.5 on 2025-01-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0002_fase1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo_fase2', models.CharField(max_length=15)),
                ('numero_bo', models.CharField(max_length=20)),
                ('data_atendimento_fase2', models.DateTimeField()),
                ('policial_responsavel', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('contato_vitima', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Houve Recusa', 'Houve Recusa')], max_length=20)),
                ('status_fase2', models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Concluída', 'Concluída'), ('Desistência na Fase 2', 'Desistência na Fase 2')], max_length=100)),
            ],
        ),
    ]
