# Generated by Django 5.1.5 on 2025-01-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0003_fase2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo_fase4', models.CharField(max_length=15)),
                ('data_atendimento_fase4', models.DateTimeField()),
                ('policial_finalizacao_fase4', models.CharField(max_length=100)),
                ('representou_crime', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Ação Incondicionada', 'Ação Incondicionada')], max_length=20)),
                ('agressao', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Prejudicado', 'Prejudicado')], max_length=20)),
                ('situacao_mpu', models.CharField(choices=[('Deferida', 'Deferida'), ('Indeferida', 'Indeferida'), ('Não Enviada ao TJ', 'Não Enviada ao TJ'), ('Declarou-se Incompetente', 'Declarou-se Incompetente')], max_length=30)),
                ('data_concessao_mpu', models.DateField()),
                ('mpu_enviado_ao_tj', models.CharField(choices=[('Sem Vídeo', 'Sem Vídeo'), ('Com Vídeo', 'Com Vídeo')], max_length=20)),
                ('numero_processo_protecao', models.CharField(max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('status_fase4', models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Concluída', 'Concluída'), ('Desistência na Fase 4', 'Desistência na Fase 4')], max_length=50)),
            ],
        ),
    ]
