# Generated by Django 5.1.5 on 2025-01-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0004_fase4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo_devir', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
