# Generated by Django 5.1.5 on 2025-01-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0006_midia_fase3_abrigamento_temporario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase3',
            name='data_hora_fase3',
            field=models.DateTimeField(),
        ),
    ]
