# Generated by Django 5.1.4 on 2025-01-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0007_alter_fase3_data_hora_fase3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('Fase 1', 'Fase 1'), ('Fase 2', 'Fase 2'), ('Fase 3', 'Fase 3'), ('Fase 4', 'Fase 4')], max_length=20)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('data_atendimento', models.DateTimeField(blank=True, null=True)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='Sistema_Poly.protocolo')),
            ],
        ),
    ]
