# Generated by Django 5.1.4 on 2025-01-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0008_protocolo_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase2',
            name='protocolo_fase2',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='protocolo_fase4',
            field=models.CharField(max_length=17),
        ),
    ]
