# Generated by Django 5.1.5 on 2025-01-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0011_alter_fase1_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase2',
            name='contato_vitima',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase2',
            name='numero_bo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase2',
            name='policial_responsavel',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='fase2',
            name='status_fase2',
            field=models.CharField(max_length=255),
        ),
    ]
