# Generated by Django 5.1.5 on 2025-01-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0012_alter_fase2_contato_vitima_alter_fase2_numero_bo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase4',
            name='agressao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='mpu_enviado_ao_tj',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='numero_processo_protecao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='policial_finalizacao_fase4',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='representou_crime',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='situacao_mpu',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='status_fase4',
            field=models.CharField(max_length=255),
        ),
    ]
