# Generated by Django 5.1.4 on 2025-01-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0014_delete_fase_delete_protocolo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fase2',
            old_name='protocolo_fase2',
            new_name='protocolo',
        ),
        migrations.RenameField(
            model_name='fase3',
            old_name='protocolo_devir',
            new_name='protocolo',
        ),
        migrations.RenameField(
            model_name='fase4',
            old_name='protocolo_fase4',
            new_name='protocolo',
        ),
    ]
