# Generated by Django 5.1.4 on 2025-01-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0015_rename_protocolo_fase2_fase2_protocolo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fase1',
            old_name='status_fase1',
            new_name='status_fase',
        ),
        migrations.RenameField(
            model_name='fase2',
            old_name='status_fase2',
            new_name='status_fase',
        ),
        migrations.RenameField(
            model_name='fase3',
            old_name='status_fase_3',
            new_name='status_fase',
        ),
        migrations.RenameField(
            model_name='fase4',
            old_name='status_fase4',
            new_name='status_fase',
        ),
    ]
