# Generated by Django 5.1.4 on 2025-01-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0016_rename_status_fase1_fase1_status_fase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase3',
            name='videoconferencia',
            field=models.CharField(default='Sim', max_length=100),
        ),
    ]
