# Generated by Django 5.1.4 on 2025-01-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0017_alter_fase3_videoconferencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fase3',
            name='consequencias_lesao',
        ),
        migrations.AlterField(
            model_name='fase3',
            name='agressao_controle',
            field=models.CharField(blank=True, help_text='O(A) agressor(a) persegue você, demonstra ciúme excessivo, tenta controlar sua vida e as coisas que você faz?', max_length=10),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='agressao_fisica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='agressao_sexual',
            field=models.CharField(blank=True, help_text='O(A) agressor(a) já obrigou você a ter relações sexuais ou praticar atos sexuais contra a sua vontade?', max_length=10),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='ameaca',
            field=models.CharField(default='Não', max_length=50),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='atendimento_medico',
            field=models.CharField(blank=True, help_text='Você necessitou de atendimento médico e/ou internação após algumas dessas agressões?', max_length=10),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='comportamentos',
            field=models.CharField(blank=True, help_text='Selecione os comportamentos do agressor', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='registro_ocorrencia',
            field=models.CharField(default='Não', max_length=3),
        ),
    ]
