# Generated by Django 5.1.4 on 2025-01-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0018_remove_fase3_consequencias_lesao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase3',
            name='agressao_frequente',
            field=models.CharField(default='Não Sei', max_length=7),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='agressao_outros',
            field=models.CharField(blank=True, help_text='Escolha as pessoas ou grupos que foram ameaçados ou agredidos.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='arma_fogo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='descumprimento_medida',
            field=models.CharField(default='Não Sei', max_length=7),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='dificuldade_financeira',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='doenca_mental',
            field=models.CharField(default='Não sei', max_length=30),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='qtd_filhos',
            field=models.CharField(default='Não possuo filhos', max_length=20),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='separacao_recente',
            field=models.CharField(default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='suicidio',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='uso_abusivo',
            field=models.CharField(default='Não', max_length=20),
        ),
    ]
