# Generated by Django 5.1.4 on 2025-01-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0019_alter_fase3_agressao_frequente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase3',
            name='ameacas_novo_relacionamento',
            field=models.CharField(default='Não Sei', max_length=10),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='conflito_guarda',
            field=models.CharField(default='Não Sei', max_length=10),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='cor_raca',
            field=models.CharField(default='Branca', help_text='Com qual cor/raça você se identifica?', max_length=10),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='deficiencia_ou_doenca',
            field=models.CharField(default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='filho_com_deficiencia',
            field=models.CharField(default='Não', max_length=20),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='filhos_com_agressor',
            field=models.CharField(default='Não', max_length=30),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='filhos_presenciaram',
            field=models.CharField(default='Não Sei', max_length=10),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='gravida_ou_bebe',
            field=models.CharField(default='Não Sei', max_length=10),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='violencia_gravidez',
            field=models.CharField(default='Não Sei', max_length=10),
        ),
    ]
