# Generated by Django 5.1.4 on 2025-01-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0020_alter_fase3_ameacas_novo_relacionamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase3',
            name='abrigamento_temporario',
            field=models.CharField(default='Não Sei', help_text='Você quer e aceita abrigamento temporário?', max_length=10),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='bairro_comunidade_rural',
            field=models.CharField(default='Não Sei', help_text='Você considera que mora em bairro, comunidade, área rural ou local de risco de violência?', max_length=10),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='dependente_financeiramente',
            field=models.CharField(default='Não Sei', help_text='Você se considera dependente financeiramente do(a) agressor(a)?', max_length=10),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='informacoes_beneficios',
            field=models.CharField(default='Não se Aplica', help_text='Deseja receber informações sobre benefícios sociais?', max_length=54),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='situacao_moradia',
            field=models.CharField(default='Própria', help_text='Qual sua situação de moradia?', max_length=10),
        ),
    ]
