# Generated by Django 5.1.4 on 2025-01-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0022_alter_fase3_agressao_relacionamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fase3',
            old_name='protocolo',
            new_name='protocolo_devir',
        ),
    ]
