# Generated by Django 5.1.4 on 2025-01-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0023_rename_protocolo_fase3_protocolo_devir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fase3',
            old_name='protocolo_devir',
            new_name='protocolo',
        ),
    ]
