# Generated by Django 5.1.4 on 2025-01-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0024_rename_protocolo_devir_fase3_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase3',
            name='abrigamento_temporario',
            field=models.CharField(default='Não Sei', help_text='Você quer e aceita abrigamento temporário?', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='agressao_controle',
            field=models.CharField(blank=True, help_text='O(A) agressor(a) persegue você, demonstra ciúme excessivo, tenta controlar sua vida e as coisas que você faz?', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='agressao_frequente',
            field=models.CharField(default='Não Sei', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='agressao_relacionamento',
            field=models.CharField(default='Não', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='agressao_sexual',
            field=models.CharField(blank=True, help_text='O(A) agressor(a) já obrigou você a ter relações sexuais ou praticar atos sexuais contra a sua vontade?', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='ajuda_registro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='alteracao_informacoes',
            field=models.CharField(default='Não', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='ameaca',
            field=models.CharField(default='Não', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='ameacas_novo_relacionamento',
            field=models.CharField(default='Não Sei', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='arma_fogo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='atendimento_medico',
            field=models.CharField(blank=True, help_text='Você necessitou de atendimento médico e/ou internação após algumas dessas agressões?', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='atendimento_medico_vitima',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='atendimento_psicologico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='bairro_comunidade_rural',
            field=models.CharField(default='Não Sei', help_text='Você considera que mora em bairro, comunidade, área rural ou local de risco de violência?', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='conflito_guarda',
            field=models.CharField(default='Não Sei', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='cor_raca',
            field=models.CharField(default='Branca', help_text='Com qual cor/raça você se identifica?', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='deficiencia_ou_doenca',
            field=models.CharField(default='Não', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='delegacia_busca_informacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='dependente_financeiramente',
            field=models.CharField(default='Não Sei', help_text='Você se considera dependente financeiramente do(a) agressor(a)?', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='descumprimento_medida',
            field=models.CharField(default='Não Sei', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='dificuldade_financeira',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='doenca_mental',
            field=models.CharField(default='Não sei', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='filho_com_deficiencia',
            field=models.CharField(default='Não', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='filhos_com_agressor',
            field=models.CharField(default='Não', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='filhos_presenciaram',
            field=models.CharField(default='Não Sei', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='gravida_ou_bebe',
            field=models.CharField(default='Não Sei', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='informacoes_beneficios',
            field=models.CharField(default='Não se Aplica', help_text='Deseja receber informações sobre benefícios sociais?', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='policial_responsavel',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='qtd_filhos',
            field=models.CharField(default='Não possuo filhos', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='reataram_relacionamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='registro_ocorrencia',
            field=models.CharField(default='Não', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='separacao_recente',
            field=models.CharField(default='Não', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='situacao_moradia',
            field=models.CharField(default='Própria', help_text='Qual sua situação de moradia?', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='status_fase',
            field=models.CharField(default='Em Andamento', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='suicidio',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='uso_abusivo',
            field=models.CharField(default='Não', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='videoconferencia',
            field=models.CharField(default='Sim', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='violencia_gravidez',
            field=models.CharField(default='Não Sei', max_length=255),
        ),
    ]
