# Generated by Django 5.1.4 on 2025-02-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0025_alter_fase3_abrigamento_temporario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase3',
            name='status_fase',
            field=models.CharField(max_length=255),
        ),
    ]
