# Generated by Django 5.1.4 on 2025-02-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0026_alter_fase3_status_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase1',
            name='protocolo',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='fase2',
            name='protocolo',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='abrigamento_temporario',
            field=models.CharField(help_text='Você quer e aceita abrigamento temporário?', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='agressao_frequente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='agressao_relacionamento',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='alteracao_informacoes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='ameaca',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='ameacas_novo_relacionamento',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='arma_fogo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='bairro_comunidade_rural',
            field=models.CharField(help_text='Você considera que mora em bairro, comunidade, área rural ou local de risco de violência?', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='conflito_guarda',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='cor_raca',
            field=models.CharField(help_text='Com qual cor/raça você se identifica?', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='deficiencia_ou_doenca',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='dependente_financeiramente',
            field=models.CharField(help_text='Você se considera dependente financeiramente do(a) agressor(a)?', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='descumprimento_medida',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='dificuldade_financeira',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='doenca_mental',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='filho_com_deficiencia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='filhos_com_agressor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='filhos_presenciaram',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='gravida_ou_bebe',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='informacoes_beneficios',
            field=models.CharField(help_text='Deseja receber informações sobre benefícios sociais?', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='qtd_filhos',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='registro_ocorrencia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='separacao_recente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='situacao_moradia',
            field=models.CharField(help_text='Qual sua situação de moradia?', max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='suicidio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='uso_abusivo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='videoconferencia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='violencia_gravidez',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='protocolo',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
