# Generated by Django 5.1.4 on 2025-02-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0027_alter_fase1_protocolo_alter_fase2_protocolo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase3',
            name='medidas_protetivas',
            field=models.TextField(blank=True),
        ),
    ]
