# Generated by Django 5.1.4 on 2025-02-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0028_alter_fase3_medidas_protetivas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase3',
            name='abrigamento_temporario',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='agressao_controle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='agressao_outros',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='agressao_sexual',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='atendimento_medico',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='bairro_comunidade_rural',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='como_soube',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='comportamentos',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='cor_raca',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='dependente_financeiramente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='informacoes_beneficios',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='motivos_retorno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='situacao_moradia',
            field=models.CharField(max_length=255),
        ),
    ]
