# Generated by Django 5.1.4 on 2025-02-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0030_alter_fase3_advogado_ou_defensor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase3',
            name='dependentes_nome_idade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='moradia_cedida',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='natureza_dos_crimes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
