# Generated by Django 5.1.4 on 2025-02-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0031_alter_fase3_dependentes_nome_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase3',
            name='numero_processo_mpu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
