# Generated by Django 5.1.4 on 2025-02-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0032_alter_fase3_numero_processo_mpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase1',
            name='bairro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase1',
            name='cidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase1',
            name='data_fato',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='fase1',
            name='dp_apuracao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase1',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='fase1',
            name='natureza',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase1',
            name='policial_validacao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase1',
            name='registro_comunicacao',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='fase1',
            name='status_fase',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase1',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='fase1',
            name='validacao_dev',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='fase2',
            name='contato_vitima',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase2',
            name='data_atendimento_fase2',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='fase2',
            name='numero_bo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase2',
            name='policial_responsavel',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='fase2',
            name='status_fase',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='abrigamento_temporario',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='agressao_frequente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='agressao_relacionamento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='alteracao_informacoes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='ameaca',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='ameacas_novo_relacionamento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='arma_fogo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='bairro_comunidade_rural',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='conflito_guarda',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='cor_raca',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='data_hora_fase3',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='deficiencia_ou_doenca',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='dependente_financeiramente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='descumprimento_medida',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='dificuldade_financeira',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='doenca_mental',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='filho_com_deficiencia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='filhos_com_agressor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='filhos_presenciaram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='gravida_ou_bebe',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='informacoes_beneficios',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='policial_responsavel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='qtd_filhos',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='registro_ocorrencia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='separacao_recente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='situacao_moradia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='status_fase',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='suicidio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='uso_abusivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='videoconferencia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='violencia_gravidez',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='agressao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='data_atendimento_fase4',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='data_concessao_mpu',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='mpu_enviado_ao_tj',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='numero_processo_protecao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='policial_finalizacao_fase4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='representou_crime',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='situacao_mpu',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='status_fase',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
