# Generated by Django 5.1.4 on 2025-02-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0033_alter_fase1_bairro_alter_fase1_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase1',
            name='data_fato',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fase1',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fase1',
            name='registro_comunicacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fase1',
            name='validacao_dev',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fase2',
            name='data_atendimento_fase2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fase2',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='data_hora_fase3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='data_concessao_mpu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
