# Generated by Django 5.1.4 on 2025-02-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Poly', '0036_alter_fase2_contato_vitima_alter_fase2_numero_bo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase2',
            name='protocolo',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fase3',
            name='protocolo',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fase4',
            name='protocolo',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
    ]
